name: Build Lazarus Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Lazarus Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Clonar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3
      # Instalar Lazarus e FPC
      - name: Install Lazarus and FPC on Windows
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          choco install lazarus --version=2.2.6

      - name: Install Lazarus and FPC on Ubuntu
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          choco install lazarus --version=2.2.6

      - name: Install Lazarus and FPC on MacOS
        if: ${{ contains(matrix.os, 'macos') }}
        run: |
          brew install fpc lazarus

      # Compilar o projeto
      - name: Compile project
        run: |
          lazbuild --build-mode=Release project1.lpi

      # Fazer upload dos artefatos gerados
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build-${{ matrix.os }}
          path: |
            *.exe
            *.app
            ./bin/
